FROM mcr.microsoft.com/dotnet/sdk AS dotnet_restore
WORKDIR /src
COPY "WebApi.sln" "WebApi.sln"
COPY "__tests__/WebApi.Api.Tests/WebApi.Api.Tests.csproj" "__tests__/WebApi.Api.Tests/WebApi.Api.Tests.csproj"
COPY "__tests__/WebApi.Business.Tests/WebApi.Business.Tests.csproj" "__tests__/WebApi.Business.Tests/WebApi.Business.Tests.csproj"
COPY "__tests__/WebApi.InfraData.Tests/WebApi.InfraData.Tests.csproj" "__tests__/WebApi.InfraData.Tests/WebApi.InfraData.Tests.csproj"
COPY "__tests__/WebApi.IntegrationTest/WebApi.IntegrationTest.csproj" "__tests__/WebApi.IntegrationTest/WebApi.IntegrationTest.csproj"
COPY "__tests__/WebApi.Shared.Tests/WebApi.Shared.Tests.csproj" "__tests__/WebApi.Shared.Tests/WebApi.Shared.Tests.csproj"
COPY "src/WebApi.Api/WebApi.Api.csproj" "src/WebApi.Api/WebApi.Api.csproj"
COPY "src/WebApi.Business/WebApi.Business.csproj" "src/WebApi.Business/WebApi.Business.csproj"
COPY "src/WebApi.InfraData/WebApi.InfraData.csproj" "src/WebApi.InfraData/WebApi.InfraData.csproj"
COPY "src/WebApi.IoC/WebApi.IoC.csproj" "src/WebApi.IoC/WebApi.IoC.csproj"
COPY "src/WebApi.Shared/WebApi.Shared.csproj" "src/WebApi.Shared/WebApi.Shared.csproj"
COPY "src/WebApi.WarmUp/WebApi.WarmUp.csproj" "src/WebApi.WarmUp/WebApi.WarmUp.csproj"
RUN dotnet restore "WebApi.sln"

FROM dotnet_restore AS dotnet_publish
WORKDIR /src
COPY . .
RUN dotnet publish "WebApi.sln" -c Release -o /app 

FROM mcr.microsoft.com/dotnet/aspnet AS runtime
WORKDIR /app
COPY --from=dotnet_publish /app .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "WebApi.Api.dll"]
