version: "3.1"

networks:
  backend:
    driver: bridge
  frontend:

services:
  sqlserver:
    build:
      context: ./sqlserver/scripts/.
      dockerfile: sqlserver.dockerFile
    ports:
      - "1433:1433"
    networks:
      - backend
      - frontend

  webapi:
    build:
      context: ../../
      dockerfile: ./eng/docker/dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Data Source=sqlserver; Initial Catalog=TemplateDB; User Id=sa; Password=MyP4ssw0rd_; Pooling=True; Min Pool Size=100; Max Pool Size=300
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
    depends_on:
      - sqlserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
